const CONFIG_COMMENTS = {
    "api.apiDebug": "是否调试http api,启用调试后，会打印每次http请求的内容和回复",
    "api.secret": "一些比较敏感的http api在访问时需要提供secret，否则无权限调用。如果是通过127.0.0.1访问,那么可以不提供secret",
    "api.snapRoot": "截图保存路径根目录，截图通过http api(/index/api/getSnap)生成和获取",
    "api.defaultSnap": "默认截图图片，在启动FFmpeg截图后但是截图还未生成时，可以返回默认的预设图片",
    "api.downloadRoot": "downloadFile http接口可访问文件的根目录，支持多个目录，不同目录通过分号(;)分隔",
    "api.legacyAuth": "是否采用传统secret硬编码鉴权模式，默认开启，开启后每次http接口请求都需要传递secret。关闭传统鉴权模式后，需要先调用/index/api/login接口登录",
    "api.mem_pic_capacity": "内存图片缓存容量",
    "api.save_mem_pic": "是否保存内存图片",
    "api.modelRoot": "模型文件根目录",
    
    "ffmpeg.bin": "FFmpeg可执行程序路径,支持相对路径/绝对路径",
    "ffmpeg.cmd": "FFmpeg拉流再推流的命令模板，通过该模板可以设置再编码的一些参数",
    "ffmpeg.snap": "FFmpeg生成截图的命令，可以通过修改该配置改变截图分辨率或质量",
    "ffmpeg.log": "FFmpeg日志的路径，如果置空则不生成FFmpeg日志。可以为相对(相对于本可执行程序目录)或绝对路径",
    "ffmpeg.restart_sec": "自动重启的时间(秒), 默认为0, 也就是不自动重启. 主要是为了避免长时间ffmpeg拉流导致的不同步现象",
    
    "protocol.modify_stamp": "转协议时，是否开启帧级时间戳覆盖。0:采用源视频流绝对时间戳；1:采用zlmediakit接收数据时的系统时间戳；2:采用源视频流时间戳相对时间戳",
    "protocol.enable_audio": "转协议是否开启音频",
    "protocol.add_mute_audio": "添加acc静音音频，在关闭音频时，此开关无效",
    "protocol.auto_close": "无人观看时，是否直接关闭(而不是通过on_none_reader hook返回close)",
    "protocol.demux_frame": "是否解复用ts/ps的帧",
    "protocol.continue_push_ms": "推流断开后可以在超时时间内重新连接上继续推流，这样播放器会接着播放。置0关闭此特性",
    "protocol.paced_sender_ms": "平滑发送定时器间隔，单位毫秒，置0则关闭；开启后影响cpu性能同时增加内存",
    "protocol.enable_hls": "是否开启转换为hls(mpegts)",
    "protocol.enable_hls_fmp4": "是否开启转换为hls(fmp4)",
    "protocol.enable_mp4": "是否开启MP4录制",
    "protocol.enable_rtsp": "是否开启转换为rtsp/webrtc",
    "protocol.enable_rtmp": "是否开启转换为rtmp/flv",
    "protocol.enable_ts": "是否开启转换为http-ts/ws-ts",
    "protocol.enable_fmp4": "是否开启转换为http-fmp4/ws-fmp4",
    "protocol.mp4_as_player": "是否将mp4录制当做观看者",
    "protocol.mp4_max_second": "mp4切片大小，单位秒",
    "protocol.mp4_save_path": "mp4录制保存路径",
    "protocol.hls_save_path": "hls录制保存路径",
    "protocol.hls_demand": "hls协议是否按需生成，如果hls.segNum配置为0(意味着hls录制)，那么hls将一直生成",
    "protocol.rtsp_demand": "rtsp[s]协议是否按需生成",
    "protocol.rtmp_demand": "rtmp[s]、http[s]-flv、ws[s]-flv协议是否按需生成",
    "protocol.ts_demand": "http[s]-ts协议是否按需生成",
    "protocol.fmp4_demand": "http[s]-fmp4、ws[s]-fmp4协议是否按需生成",
    "protocol.enable_transcode_mp4": "是否开启转码录制mp4",
    
    "general.enableVhost": "是否启用虚拟主机",
    "general.flowThreshold": "播放器或推流器在断开后会触发hook.on_flow_report事件阈值，使用流量超过该阈值后才触发，单位KB",
    "general.maxStreamWaitMS": "播放最多等待时间，单位毫秒。播放在播放某个流时，如果该流不存在，ZLMediaKit会最多让播放器等待maxStreamWaitMS毫秒",
    "general.streamNoneReaderDelayMS": "某个流无人观看时，触发hook.on_stream_none_reader事件的最大等待时间，单位毫秒",
    "general.resetWhenRePlay": "拉流代理时如果断流再重连成功是否删除前一次的媒体流数据",
    "general.mergeWriteMS": "合并写缓存大小(单位毫秒)，合并写指服务器缓存一定的数据后才会一次性写入socket",
    "general.mediaServerId": "服务器唯一id，用于触发hook时区别是哪台服务器",
    "general.wait_track_ready_ms": "最多等待未初始化的Track时间，单位毫秒，超时之后会忽略未初始化的Track",
    "general.wait_audio_track_data_ms": "最多等待音频Track收到数据时间，单位毫秒，超时且完全没收到音频数据，忽略音频Track",
    "general.wait_add_track_ms": "如果流只有单Track，最多等待若干毫秒，超时后未收到其他Track的数据，则认为是单Track",
    "general.unready_frame_cache": "如果track未就绪，我们先缓存帧数据，但是有最大个数限制，防止内存溢出",
    "general.broadcast_player_count_changed": "是否启用观看人数变化事件广播，置1则启用，置0则关闭",
    "general.listen_ip": "绑定的本地网卡ip",
    
    "hls.fileBufSize": "hls写文件的buf大小，调整参数可以提高文件io性能",
    "hls.segDur": "hls最大切片时间",
    "hls.segNum": "m3u8索引中,hls保留切片个数(实际保留切片个数+segRetain个)。如果设置为0，则不删除切片且m3u8文件全量记录切片列表",
    "hls.segDelay": "HLS切片延迟个数，大于0将生成hls_delay.m3u8文件，0则不生成",
    "hls.segRetain": "HLS切片从m3u8文件中移除后，继续保留在磁盘上的个数",
    "hls.broadcastRecordTs": "是否广播 hls切片(ts/fmp4)完成通知(on_record_ts)",
    "hls.deleteDelaySec": "直播hls文件删除延时，单位秒",
    "hls.segKeep": "此选项开启后m3u8文件还是表现为直播，但是切片文件会被全部保留为点播用",
    "hls.fastRegister": "如果设置为1，则第一个切片长度强制设置为1个GOP。当GOP小于segDur，可以提高首屏速度",
    
    "hook.enable": "是否启用hook事件，启用后，推拉流都将进行鉴权",
    "hook.on_flow_report": "播放器或推流器使用流量事件，置空则关闭",
    "hook.on_http_access": "访问http文件鉴权事件，置空则关闭鉴权",
    "hook.on_play": "播放鉴权事件，置空则关闭鉴权",
    "hook.on_publish": "推流鉴权事件，置空则关闭鉴权",
    "hook.on_record_mp4": "录制mp4切片完成事件",
    "hook.on_record_ts": "录制 hls ts(或fmp4) 切片完成事件",
    "hook.on_rtsp_auth": "rtsp播放鉴权事件，此事件中比对rtsp的用户名密码",
    "hook.on_rtsp_realm": "rtsp播放是否开启专属鉴权事件，置空则关闭rtsp鉴权",
    "hook.on_shell_login": "远程telnet调试鉴权事件",
    "hook.on_stream_changed": "直播流注册或注销事件",
    "hook.stream_changed_schemas": "过滤on_stream_changed hook的协议类型，可以选择只监听某些感兴趣的协议；置空则不过滤协议",
    "hook.on_stream_none_reader": "无人观看流事件，通过该事件，可以选择是否关闭无人观看的流",
    "hook.on_stream_not_found": "播放时，未找到流事件，通过配合hook.on_stream_none_reader事件可以完成按需拉流",
    "hook.on_server_started": "服务器启动报告，可以用于服务器的崩溃重启事件监听",
    "hook.on_server_exited": "服务器退出报告，当服务器正常退出时触发",
    "hook.on_server_keepalive": "server保活上报",
    "hook.on_send_rtp_stopped": "发送rtp(startSendRtp)被动关闭时回调",
    "hook.on_rtp_server_timeout": "rtp server 超时未收到数据",
    "hook.timeoutSec": "hook api最大等待回复时间，单位秒",
    "hook.alive_interval": "keepalive hook触发间隔,单位秒，float类型",
    "hook.retry": "hook通知失败重试次数,正整数。为0不重试，1时重试一次，以此类推",
    "hook.retry_delay": "hook通知失败重试延时，单位秒，float型",
    
    "cluster.origin_url": "设置源站拉流url模板, 格式跟printf类似，第一个%s指定app,第二个%s指定stream_id",
    "cluster.timeout_sec": "溯源总超时时长，单位秒，float型",
    "cluster.retry_count": "溯源失败尝试次数，-1时永久尝试",
    
    "http.charSet": "http服务器字符编码集",
    "http.keepAliveSecond": "http链接超时时间",
    "http.maxReqSize": "http请求体最大字节数，如果post的body太大，则不适合缓存body在内存",
    "http.notFound": "404网页内容，用户可以自定义404网页",
    "http.port": "http服务器监听端口",
    "http.rootPath": "http文件服务器根目录，可以为相对(相对于本可执行程序目录)或绝对路径",
    "http.sendBufSize": "http文件服务器读文件缓存大小，单位BYTE，调整该参数可以优化文件io性能",
    "http.sslport": "https服务器监听端口",
    "http.dirMenu": "是否显示文件夹菜单，开启后可以浏览文件夹",
    "http.virtualPath": "虚拟目录, 虚拟目录名和文件路径使用\",\"隔开，多个配置路径间用\";\"隔开",
    "http.forbidCacheSuffix": "禁止后缀的文件使用mmap缓存，使用\",\"隔开",
    "http.forwarded_ip_header": "可以把http代理前真实客户端ip放在http头中",
    "http.allow_cross_domains": "默认允许所有跨域请求",
    "http.allow_ip_range": "允许访问http api和http文件索引的ip地址范围白名单，置空情况下不做限制",
    
    "multicast.addrMax": "rtp组播截止组播ip地址",
    "multicast.addrMin": "rtp组播起始组播ip地址",
    "multicast.udpTTL": "组播udp ttl",
    
    "record.appName": "mp4录制或mp4点播的应用名，通过限制应用名，可以防止随意点播",
    "record.fileBufSize": "mp4录制写文件缓存，单位BYTE,调整参数可以提高文件io性能",
    "record.sampleMS": "mp4点播每次流化数据量，单位毫秒",
    "record.fastStart": "mp4录制完成后是否进行二次关键帧索引写入头部",
    "record.fileRepeat": "MP4点播(rtsp/rtmp/http-flv/ws-flv)是否循环播放文件",
    "record.enableFmp4": "MP4录制写文件格式是否采用fmp4，启用的话，断电未完成录制的文件也能正常打开",
    "record.max_delta_stamp_ms": "最大时间戳增量，单位毫秒",
    
    "rtmp.handshakeSecond": "rtmp必须在此时间内完成握手，否则服务器会断开链接，单位秒",
    "rtmp.keepAliveSecond": "rtmp超时时间，如果该时间内未收到客户端的数据，或者tcp发送缓存超过这个时间，则会断开连接，单位秒",
    "rtmp.port": "rtmp服务器监听端口",
    "rtmp.sslport": "rtmps服务器监听地址",
    "rtmp.directProxy": "rtmp是否直接代理模式",
    "rtmp.enhanced": "h265/opus/vp8/vp9/av1 rtmp打包采用增强型rtmp标准还是国内拓展标准",
    
    "rtp.audioMtuSize": "音频mtu大小，该参数限制rtp最大字节数，推荐不要超过1400",
    "rtp.videoMtuSize": "视频mtu大小，该参数限制rtp最大字节数，推荐不要超过1400",
    "rtp.rtpMaxSize": "rtp包最大长度限制，单位KB,主要用于识别TCP上下文破坏时，获取到错误的rtp",
    "rtp.lowLatency": "rtp 打包时，低延迟开关，默认关闭",
    "rtp.h264_stap_a": "H264 rtp打包模式是否采用stap-a模式",
    
    "rtp_proxy.dumpDir": "导出调试数据(包括rtp/ps/h264)至该目录,置空则关闭数据导出",
    "rtp_proxy.port": "udp和tcp代理服务器，支持rtp(必须是ts或ps类型)代理",
    "rtp_proxy.timeoutSec": "rtp超时时间，单位秒",
    "rtp_proxy.port_range": "随机端口范围，最少确保36个端口",
    "rtp_proxy.h264_pt": "rtp h264 负载的pt",
    "rtp_proxy.h265_pt": "rtp h265 负载的pt",
    "rtp_proxy.ps_pt": "rtp ps 负载的pt",
    "rtp_proxy.opus_pt": "rtp opus 负载的pt",
    "rtp_proxy.aac_pt": "rtp aac 负载的pt",
    "rtp_proxy.gop_cache": "startSendRtp、startRecord相关功能是否提前开启gop缓存优化级联秒开体验",
    "rtp_proxy.rtp_g711_dur_ms": "国标发送g711 rtp 打包时，每个包的语音时长是多少，默认是100 ms",
    "rtp_proxy.udp_recv_socket_buffer": "udp接收数据socket buffer大小配置",
    "rtp_proxy.merge_frame": "ps/ts解析后是否等待下一帧以判断本帧是否完整",
    "rtp_proxy.force_tcp": "是否强制使用tcp方式代理rtp",
    
    "rtc.signalingPort": "webrtc 信令服务器端口",
    "rtc.signalingSslPort": "webrtc ssl信令服务器端口",
    "rtc.icePort": "STUN/TURN服务器端口",
    "rtc.iceTcpPort": "STUN/TURN TCP服务器端口",
    "rtc.enableTurn": "STUN/TURN端口是否使能TURN服务",
    "rtc.iceTransportPolicy": "ICE传输策略：0=不限制(默认)，1=仅支持Relay转发，2=仅支持P2P直连",
    "rtc.iceUfrag": "STUN/TURN 服务Ice用户名",
    "rtc.icePwd": "STUN/TURN 服务Ice密码",
    "rtc.datachannel_echo": "webrtc datachannel是否回显数据，测试用",
    "rtc.max_stun_retry": "最大stun重试次数",
    "rtc.port_range": "TURN服务分配端口池",
    "rtc.timeoutSec": "rtc播放推流、播放超时时间",
    "rtc.externIP": "本机对rtc客户端的可见ip，作为服务器时一般为公网ip，可有多个，用','分开",
    "rtc.interfaces": "当指定了interfaces,ICE服务器会使用指定网卡bind socket",
    "rtc.port": "rtc udp服务器监听端口号",
    "rtc.tcpPort": "rtc tcp服务器监听端口号",
    "rtc.rembBitRate": "设置remb比特率，非0时关闭twcc并开启remb",
    "rtc.preferredCodecA": "rtc支持的音频codec类型,在前面的优先级更高",
    "rtc.preferredCodecV": "rtc支持的视频codec类型,在前面的优先级更高",
    "rtc.start_bitrate": "webrtc起始比特率",
    "rtc.max_bitrate": "webrtc最大比特率",
    "rtc.min_bitrate": "webrtc最小比特率",
    "rtc.maxRtpCacheMS": "rtp重发缓存列队最大长度，单位毫秒",
    "rtc.maxRtpCacheSize": "rtp重发缓存列队最大长度，单位个数",
    "rtc.nackMaxSize": "最大保留的rtp丢包状态个数",
    "rtc.nackMaxMS": "rtp丢包状态最长保留时间",
    "rtc.nackMaxCount": "nack最多请求重传次数",
    "rtc.nackIntervalRatio": "nack重传频率，rtt的倍数",
    "rtc.nackRtpSize": "视频nack包中视频rtp个数",
    "rtc.nackAudioRtpSize": "音频nack包中rtp个数",
    "rtc.bfilter": "是否尝试过滤 b帧",
    "rtc.preferred_tcp": "是否优先采用webrtc over tcp模式",
    
    "srt.timeoutSec": "srt播放推流、播放超时时间,单位秒",
    "srt.port": "srt udp服务器监听端口号",
    "srt.latencyMul": "srt 协议中延迟缓存的估算参数",
    "srt.pktBufSize": "包缓存的大小",
    "srt.passPhrase": "srt udp服务器的密码,为空表示不加密",
    
    "rtsp.authBasic": "rtsp专有鉴权方式是采用base64还是md5方式",
    "rtsp.directProxy": "rtsp拉流、推流代理是否是直接代理模式",
    "rtsp.handshakeSecond": "rtsp必须在此时间内完成握手，否则服务器会断开链接，单位秒",
    "rtsp.keepAliveSecond": "rtsp超时时间，如果该时间内未收到客户端的数据，或者tcp发送缓存超过这个时间，则会断开连接，单位秒",
    "rtsp.port": "rtsp服务器监听地址",
    "rtsp.sslport": "rtsps服务器监听地址",
    "rtsp.lowLatency": "rtsp 转发是否使用低延迟模式",
    "rtsp.rtpTransportType": "强制协商rtp传输方式 (0:TCP,1:UDP,2:MULTICAST,-1:不限制)",
    
    "shell.maxReqSize": "调试telnet服务器接受最大buffer大小",
    "shell.port": "调试telnet服务器监听端口",
    
    "onvif.port": "onvif搜索端口",
    
    "1078.modify_audio_stamp": "1078协议是否修改音频时间戳",
    "1078.add_audio_prefix": "1078协议是否添加音频前缀",
    "1078.check_payload_len": "1078协议是否检查payload长度",
    
    "awss3.key": "AWS S3访问密钥",
    "awss3.secret": "AWS S3访问密钥密码",
    "awss3.region": "AWS S3区域",
    "awss3.url": "AWS S3服务URL",
    
    "python.plugin": "Python插件路径"
};
